/// Flutter icons MyIconPack
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIconPack
///      fonts:
///       - asset: fonts/MyIconPack.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIconPack {
  MyIconPack._();

  static const _kFontFam = 'MyIconPack';
  static const String? _kFontPkg = null;

  static const IconData flame = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plate = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
